project/alumnos/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask import Flask, render_template, request, redirect, url_for, jsonify
from flask import Blueprint
from project.models import db, Alumnos
import project.forms as forms

auth = Blueprint('auth', __name__, url_prefix='/auth')

@auth.route('/crear_alumnos',methods = ['GET', 'POST'])
def crear():
    create_form = forms.AlumnosForm(request.form)
    if request.method == 'POST':
        alu = Alumnos(nombre = create_form.nombre.data,
                      apaterno = create_form.apaterno.data,
                      amaterno = create_form.amaterno.data,
                      email = create_form.email.data,
                      carrera = create_form.carrera.data)
        db.session.add(alu)
        db.session.commit()
        return redirect(url_for('auth.leer'))
    return render_template('crear_alumnos.html',form = create_form)

@auth.route('/leer_alumnos',methods = ['GET', 'POST'])
def leer():
    read_form = forms.AlumnosForm(request.form)
    alumnos = Alumnos.query.all()
    return render_template('leer_alumnos.html', form = read_form, alumnos = alumnos)

@auth.route('/actualizar_alumnos',methods = ['GET', 'POST'])
def actualizar():
    update_form = forms.AlumnosForm(request.form)
    if request.method == 'GET':
        id = request.args.get('id')

        alu = db.session.query(Alumnos).filter(Alumnos.id == id).first()
        update_form.id.data = request.args.get('id')
        update_form.nombre.data = alu.nombre
        update_form.apaterno.data = alu.apaterno
        update_form.amaterno.data = alu.amaterno
        update_form.email.data = alu.email
        update_form.carrera.data = alu.carrera

    if request.method == 'POST':
        id = update_form.id.data
        alum = db.session.query(Alumnos).filter(Alumnos.id == id).first()
        alum.nombre = update_form.nombre.data
        alum.apaterno = update_form.apaterno.data
        alum.amaterno = update_form.amaterno.data
        alum.email = update_form.email.data
        alum.carrera = update_form.carrera.data

        db.session.add(alum)
        db.session.commit()
        return redirect(url_for('auth.leer'))
    
    return render_template('actualizar_alumnos.html',form = update_form)

@auth.route('/eliminar_alumnos',methods = ['GET', 'POST'])
def eliminar():
    delete_form = forms.AlumnosForm(request.form)
    if request.method == 'GET':
        id = request.args.get('id')

        alu = db.session.query(Alumnos).filter(Alumnos.id == id).first()
        delete_form.id.data = request.args.get('id')
        delete_form.nombre.data = alu.nombre
        delete_form.apaterno.data = alu.apaterno
        delete_form.amaterno.data = alu.amaterno
        delete_form.email.data = alu.email
        delete_form.carrera.data = alu.carrera

    if request.method == 'POST':
        id = delete_form.id.data
        alum = db.session.query(Alumnos).filter(Alumnos.id == id).first()
        alum.nombre = delete_form.nombre.data
        alum.apaterno = delete_form.apaterno.data
        alum.amaterno = delete_form.amaterno.data
        alum.email = delete_form.email.data
        alum.carrera = delete_form.carrera.data

        db.session.delete(alum)
        db.session.commit()
        
        return redirect(url_for('auth.leer'))
    return render_template('eliminar_alumnos.html', form = delete_form)

project/maestros/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask import Flask, render_template, request, redirect, url_for, jsonify
from flask import Blueprint
from project.models import db, Maestros
import project.forms as forms
from ..db import get_connection



ma = Blueprint('ma', __name__, url_prefix='/ma')

@ma.route('/crear_maestros',methods = ['GET', 'POST'])
def insert_maestro():
    create_form = forms.MaestrosForm(request.form)
    if request.method == 'POST':
        nombre=create_form.nombre.data,
        apaterno=create_form.apaterno.data,
        amaterno=create_form.amaterno.data,
        email=create_form.email.data,
        telefono=create_form.telefono.data
        

        connection=get_connection()
        with connection.cursor() as cursor:
            cursor.execute('CALL create_maestro(%s,%s,%s,%s,%s) ',(nombre,apaterno,amaterno,email,telefono))
        connection.commit()
        connection.close()
               
        
        return redirect(url_for('ma.leer'))
    return render_template('crear_maestros.html',form=create_form)



@ma.route('/leer_maestros',methods = ['GET', 'POST'])
def leer():
    connection = get_connection()
    with connection.cursor() as cursor:
        cursor.execute('CALL get_maestros()')
        maestros = cursor.fetchall()
    return render_template('leer_maestros.html',maestros=maestros)

@ma.route('/actualizar_maestros',methods = ['GET', 'POST'])
def actualizar():
    update_form = forms.MaestrosForm(request.form)
   
    
    if request.method == 'GET':
        id=request.args.get('id')
        ma = db.session.query(Maestros).filter(Maestros.id == id).first()
        update_form.id.data = request.args.get('id')
        update_form.nombre.data = ma.nombre
        update_form.apaterno.data = ma.apaterno
        update_form.amaterno.data = ma.amaterno
        update_form.email.data = ma.email
        update_form.telefono.data = ma.telefono
        
    if request.method == 'POST':
        id = update_form.id.data
        nombre=update_form.nombre.data
        apaterno=update_form.apaterno.data
        amaterno=update_form.amaterno.data
        email=update_form.email.data
        telefono=update_form.telefono.data
       
     
        connection=get_connection()
        with connection.cursor() as cursor:
            cursor.execute('CALL update_maestro(%s,%s,%s,%s,%s,%s) ',(id,nombre,apaterno,amaterno,email,telefono))
        connection.commit()
        connection.close()
               
        
        return redirect(url_for('ma.leer'))
    return render_template('actualizar_maestros.html',form=update_form)

@ma.route('/eliminar_maestros',methods = ['GET', 'POST'])
def eliminar():
    delete_form = forms.MaestrosForm(request.form)
    if request.method == 'GET':
            id=request.args.get('id')
            ma = db.session.query(Maestros).filter(Maestros.id == id).first()
            delete_form.id.data = request.args.get('id')
            delete_form.nombre.data = ma.nombre
            delete_form.apaterno.data = ma.apaterno
            delete_form.amaterno.data = ma.amaterno
            delete_form.email.data = ma.email
            delete_form.telefono.data = ma.telefono
        
    if request.method == 'POST':
        id = delete_form.id.data
        
       
     
        connection=get_connection()
        with connection.cursor() as cursor:
            cursor.execute('CALL delete_maestro(%s) ',(id))
        connection.commit()
        connection.close()
               
        
        return redirect(url_for('ma.leer'))
    return render_template('eliminar_maestros.html',form=delete_form)

project/templates/_macros.html
{%macro render_field(field)%}
    <div class="control-group">
        <div class="controls">
            {{field.label}}
            
            {{field(**kwargs)|safe}}
        </div>
    </div>

    {%if field.errors%}
        <ul>
            {%for error in field.errors%}
                <li style = "color: red">
                    {{error}}
                </li>
            {%endfor%}
        </ul>
    {%endif%}
{%endmacro%}

project/templates/actualizar_alumnos.html
{% extends "navbar.html" %}

{% block content %}

    {% from "_macros.html" import render_field %}

    <div class="container">
        <div class="row">
            <form name = "sent" action = "/auth/actualizar_alumnos" id = "form1" method = "POST">
                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.id, class = 'form-control')}}
                    </div>
                </div>
                
                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.nombre, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.apaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.amaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.email, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.carrera, class = 'form-control')}}
                    </div>
                </div>

                <input type = "hidden" name = "csrf_token" value = "{{csrf_token()}}"/>
                <a href="{{ url_for('auth.leer') }}" class="btn btn-danger">Cancelar</a>
                <input type = "submit" class = "btn btn-warning" id = "reg_alum" name = "update" value = "Modificar"/>
            </form>
        </div>
    </div>

{% endblock %}

project/templates/actualizar_maestros.html
{% extends "navbar.html" %}

{% block content %}

    {% from "_macros.html" import render_field %}

    <div class="container">
        <div class="row">
            <form name = "sent" action = "/ma/actualizar_maestros" id = "form1" method = "POST">
                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.id, class = 'form-control')}}
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.nombre, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.apaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.amaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.email, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.telefono, class = 'form-control')}}
                    </div>
                </div>

                <input type = "hidden" name = "csrf_token" value = "{{csrf_token()}}"/>
                <a href="{{ url_for('ma.leer') }}" class="btn btn-secondary">Cancelar</a>
                <input type = "submit" class = "btn btn-success" id = "reg_alum" name = "registra" value = "Registrar">
            </form>
        </div>
    </div>

{% endblock %}

project/templates/crear_alumnos.html
{% extends "navbar.html" %}

{% block content %}

    {% from "_macros.html" import render_field %}

    <div class="container">
        <div class="row">
            <form name = "sent" action = "/auth/crear_alumnos" id = "form1" method = "POST">
                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.nombre, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.apaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.amaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.email, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.carrera, class = 'form-control')}}
                    </div>
                </div>

                <input type = "hidden" name = "csrf_token" value = "{{csrf_token()}}"/>
                <a href="{{ url_for('auth.leer') }}" class="btn btn-secondary">Cancelar</a>
                <input type = "submit" class = "btn btn-success" id = "reg_alum" name = "registra" value = "Registrar">
            </form>
        </div>
    </div>

{% endblock %}

project/templates/crear_maestros.html
{% extends "navbar.html" %}

{% block content %}

    {% from "_macros.html" import render_field %}

    <div class="container">
        <div class="row">
            <form name = "sent" action = "/ma/crear_maestros" id = "form1" method = "POST">
                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.nombre, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.apaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.amaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.email, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.telefono, class = 'form-control')}}
                    </div>
                </div>

                <input type = "hidden" name = "csrf_token" value = "{{csrf_token()}}"/>
                <a href="{{ url_for('ma.leer') }}" class="btn btn-secondary">Cancelar</a>
                <input type = "submit" class = "btn btn-success" id = "reg_alum" name = "registra" value = "Registrar">
            </form>
        </div>
    </div>

{% endblock %}

project/templates/eliminar_alumnos.html
{% extends "navbar.html" %}

{% block content %}

    {% from "_macros.html" import render_field %}

    <div class="container">
        <div class="row">
            <form name = "sent" action = "/auth/eliminar_alumnos" id = "form1" method = "POST">
                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.id, class = 'form-control')}}
                    </div>
                </div>
                
                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.nombre, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.apaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.amaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.email, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.carrera, class = 'form-control')}}
                    </div>
                </div>

                <input type = "hidden" name = "csrf_token" value = "{{csrf_token()}}"/>
                <a href="{{ url_for('auth.leer') }}" class="btn btn-secondary">Cancelar</a>
                <input type = "submit" class = "btn btn-danger" id = "reg_alum" name = "delete" value = "Eliminar"/>
            </form>
        </div>
    </div>

{% endblock %}

project/templates/eliminar_maestros.html
{% extends "navbar.html" %}

{% block content %}

    {% from "_macros.html" import render_field %}

    <div class="container">
        <div class="row">
            <form name = "sent" action = "/ma/eliminar_maestros" id = "form1" method = "POST">
                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.id, class = 'form-control')}}
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.nombre, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.apaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.amaterno, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.email, class = 'form-control')}}
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 float-label-form-group controls">
                        {{render_field(form.telefono, class = 'form-control')}}
                    </div>
                </div>

                <input type = "hidden" name = "csrf_token" value = "{{csrf_token()}}"/>
                <a href="{{ url_for('ma.leer') }}" class="btn btn-secondary">Cancelar</a>
                <input type = "submit" class = "btn btn-danger" id = "reg_alum" name = "registra" value = "Eliminar">
            </form>
        </div>
    </div>

{% endblock %}

project/templates/index.html
{% extends "navbar.html" %}

{% block content %}

    <h1>Pagina de inicio</h1>
    <img src="https://universidadesdemexico.mx/logos/original/logo-universidad-tecnologica-de-leon.webp" alt="">
{% endblock %}

project/templates/leer_alumnos.html
{% extends "navbar.html" %}

{% block content %}
    <h2>Estudiantes</h2>
    {% from "_macros.html" import render_field %}

    <div class="container">
        <div class="row">
            <a href="{{ url_for('auth.crear') }}" class="btn btn-success">
                Agregar <i class="icon-plus-sign icon-white"></i></a>
            <table class="table table">
                <thead>
                    <tr>
                        <th>NOMBRE(S)</th>
                        <th>APELLIDO PATERNO</th>
                        <th>APELLIDO MATERNO</th>
                        <th>CORREO</th>
                        <th>CARRERA</th>
                        <th>ACCIONES</th>
                    </tr>
                </thead>
                <tbody>
                    {% for alu in alumnos %}
                    <tr>
                        <td>{{alu.nombre}}</td>
                        <td>{{alu.apaterno}}</td>
                        <td>{{alu.amaterno}}</td>
                        <td>{{alu.email}}</td>
                        <td>{{alu.carrera}}</td>
                        <td><a href="{{ url_for('auth.eliminar') }}?id={{alu.id}}" class="btn btn-danger">
                            Eliminar <i class="icon-trash icon-white"></i></a>
                        <a href="{{ url_for('auth.actualizar') }}?id={{alu.id}}" class="btn btn-warning">
                            Modificar <i class="icon-edit icon-white"></i></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

project/templates/leer_maestros.html
{% extends "navbar.html" %}

{% block content %}
<h1>Maestros</h1>
    {% from "_macros.html" import render_field %}

    <div class="container">
        <div class="row">
            <a href="{{ url_for('ma.insert_maestro') }}" class="btn btn-success">
                <i class="icon-plus-sign icon-white"></i> Agregar</a>
            <table class="table table">
                <thead>
                    <tr>
                        <th>NOMBRE</th>
                        <th>APELLIDO PATERNO</th>
                        <th>APELLIDO MATERNO</th>
                        <th>TELEFONO</th>
                        <th>CORREO</th>
                        <th>ELIMINAR</th>
                        <th>MODIFICAR</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ma in maestros %}
                    <tr>
                        <td>{{ma[1]}}</td>
                        <td>{{ma[2]}}</td>
                        <td>{{ma[3]}}</td>
                        <td>{{ma[4]}}</td>
                        <td>{{ma[5]}}</td>
                        <td><a href="{{ url_for('ma.eliminar') }}?id={{ma[0]}}" class="btn btn-danger">
                            <i class="icon-remove icon-white"></i> Eliminar</a></td>
                        <td><a href="{{ url_for('ma.actualizar') }}?id={{ma[0]}}" class="btn btn-warning">
                            <i class="icon-pencil icon-white"></i> Modificar</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

project/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="../static/bootstrap/css/bootstrap.min.css">

    <title>UTL</title>
        <style>
            body{
                padding-top: 60px;
                padding-left: 60px;
            }
            .tr-head{background: blue;}
    </style>
    <link rel="stylesheet" href="../static/bootstrap/css/bootstrap-responsive.min.css">
</head>
<body>
    <div class="navbar navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a href="/" class="brand">
                    UTL - IDGS804
                </a>
                <ul class="nav">
                    <li class="activate">
                        <a href="/">
                            <i class="icon-home icon-white"></i>
                            Inicio
                        </a>
                    </li>

                    <li>
                        <a href="{{ url_for('auth.leer') }}">
                            <i class="icon-book icon-white"></i>
                            Estudiantes
                        </a>
                    </li>

                    <li>
                        <a href="{{ url_for('ma.leer') }}">
                            <i class="icon-briefcase icon-white"></i>
                            Maestros
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    {%block content%}
    {%endblock%}
    </div>
</body>
</html>